"use client";
import React from "react";

export default function BlogIntelligencePage() {
  const articles = [
    {
      title: "Advanced Firewall Penetration Trends in 2026",
      category: "Threat Vector Matrix",
      readTime: "8 min read",
      desc: "Explore how next-generation threat groups are bypassing traditional firewall logic using polymorphic code fragments and decentralized command structures globally.",
      icon: "security_update_warning"
    },
    {
      title: "The Mechanics of Automated Zero-Day Mitigation Profiles",
      category: "SOAR Engineering",
      readTime: "12 min read",
      desc: "A breakdown of autonomous response models capable of intercepting unmapped exploit sequences at network hardware scale with minimal latency markers.",
      icon: "robot_2"
    },
    {
      title: "Sovereign Cloud Data Privacy Mandates Across West Africa",
      category: "Compliance Protocols",
      readTime: "6 min read",
      desc: "Understanding compliance adjustments required under the latest regional frameworks to secure high-volume transaction databases legally.",
      icon: "gavel"
    }
  ];

  return (
    <div className="pt-40 pb-section-gap px-margin-desktop max-w-[1536px] mx-auto">
      
      {/* Top Header Block matching original layout parameters */}
      <div className="border-b border-outline-variant/20 pb-10 mb-16 max-w-4xl">
        <div className="flex flex-wrap items-center gap-3 mb-4">
          <h1 className="text-4xl md:text-5xl font-black tracking-tight text-on-background uppercase">STRATEGIC BLOG BY</h1>
          <img src="/logo.png" alt="" className="h-8 w-auto object-contain" />
        </div>
        <p className="italic text-primary border-l-4 border-primary pl-6 py-1 mb-6 text-xl font-bold">
          High-Signal Cyber Threat Intelligence &amp; Technical Analysis
        </p>
        <p className="text-on-surface-variant text-base leading-relaxed">
          Stay continuously informed with real-time vector analysis, deep platform vulnerability documentation, and verified system security reports generated by our analyst divisions.
        </p>
      </div>

      {/* Main Blog Article Feed Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-gutter">
        {articles.map((art, idx) => (
          <article key={idx} className="bg-surface-container-lowest border border-outline-variant/30 p-8 rounded-lg flex flex-col justify-between transition-all duration-300 hover:-translate-y-2 hover:shadow-xl group cursor-pointer">
            <div>
              <div className="text-primary mb-6">
                <span className="material-symbols-outlined text-4xl group-hover:scale-105 transition-transform">{art.icon}</span>
              </div>
              <div className="flex justify-between items-center text-xs font-bold text-on-surface-variant/70 uppercase tracking-wider mb-4">
                <span>{art.category}</span>
                <span className="font-mono">{art.readTime}</span>
              </div>
              <h3 className="text-xl font-bold text-on-surface mb-4 leading-snug group-hover:text-primary transition-colors">
                {art.title}
              </h3>
              <p className="text-sm text-on-surface-variant leading-relaxed mb-8 opacity-90">
                {art.desc}
              </p>
            </div>
            <div className="pt-4 border-t border-outline-variant/10 flex items-center justify-between text-xs font-bold uppercase tracking-wider text-primary group-hover:gap-4 transition-all">
              <span>Read Full Briefing</span>
              <span className="material-symbols-outlined text-sm">arrow_forward</span>
            </div>
          </article>
        ))}
      </div>

    </div>
  );
}